# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0004_auto_20180419_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='video_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='lyrics_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics_list', to='django_api.LyricsCollection'),
        ),
    ]
